# Generated by Django 4.2.4 on 2023-08-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('uid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=255)),
                ('short_url', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
